apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-chessboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-chessboard
  template:
    metadata:
      labels:
        app: react-chessboard
    spec:
      containers:
      - name: react-chessboard-container
        image: hemantrana/react-chessboard:latest
        ports:
        - containerPort: 80
