apiVersion: v1
kind: Service
metadata:
  name: react-chessboard-service
spec:
  selector:
    app: react-chessboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
